### ISSUE TITLE
Add Support For Slack Notifications

### ISSUE THREAD

**Issue by jacques-n** [sundeck-io/OpsCenter#25]
We need to enhance the probe notifications to support Slack notification. Let's plan to stub out how to support this in OpsCenter here.

**Comment by joshelser** [comment]
I've been playing around with how to make a basic Slack app to make this happen. I'll write something up.

**Comment by joshelser** [comment]
My plan for Slack notifications is to mimic what we have done already for email notifications. When a probe condition matches, we will ultimately call an external function (likely, reusing the existing `ef_notification` we already have).

We'll have to tease apart some of the probe logic/UI today. Ideally, we push down the "mechanism" of notification as an implementation detail, letting us delegate logic to the specific mechanism of notification in an object-oriented style).

For example, rather than probes having "Email the Author" and "Email others", we'll change this to "Notify the author" and "Notify others". Then, when enabling one of these options, the user can choose to "notify by email" or "notify by slack".

**Comment by jacques-n** [comment]
Sounds like a good approach. Thanka for taking this on.
