### ISSUE TITLE
Unable to create ungrouped label in Cypress test

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#39]
Have noticed Cypress tests that create an ungrouped label have failed with the error "Invalid SQL condition ... syntax error on line 3 at position 1 unexpected 'then'".

This has only been observed in Cypress. We're unsure if there is some workaround that can be done in the Cypress test to work around this or if it's some other kind of bug.

**Comment by vqmarkman** [comment]
Assigned to myself to check in test and validate this behavior again.

**Comment by vqmarkman** [comment]
The problem here is that (a) label creation worked when submitted manually (b) when ran with cypress automation, condition field ended up being empty despite the fact that input was typed in, sending empty string parameter to create_label stored procedure:
`CALL ADMIN.CREATE_LABEL('label_150c147d-9f36-48fd-8cfa-e2c6c5f57a22', NULL, NULL, '');`

Adding wait did not help, however, I noticed that st.text_area requires input submission, see below in blue:

![New label](https://github.com/sundeck-io/OpsCenter/assets/104043363/7508c1b9-e147-46c7-8746-2a6e7cf9c1e8)

This cypress workaround seems to work:

```
  cy.get('textarea[aria-label="Condition"]')
    .clear()
    .type(condition).type('{command+enter}'); <--- note sending "command+enter" after submission.
```

I will be adding test for ungrouped labels back shortly. cc @doronrosenberg

**Comment by joshelser** [comment]
Great find, Vicky!
